# Generated by Django 5.2.7 on 2025-10-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_remove_task_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['week_number', 'task_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='is_scheduled',
            field=models.BooleanField(default=False, help_text='Is this a scheduled task?'),
        ),
        migrations.AddField(
            model_name='task',
            name='release_date',
            field=models.DateTimeField(blank=True, help_text='Date when task becomes available to students', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='week_number',
            field=models.IntegerField(default=1, help_text='Week number in the course (1, 2, 3, etc.)'),
        ),
    ]
